### ISSUE TITLE
Move callbacks to glfwCallbacks.c

### ISSUE THREAD

**Issue by Boris00035** [Iosybe/particleSimulation#12]

**Comment by Boris00035** [comment]
moet ff nadat window global var is, anders kunnen de callbacks niet bij de window var

**Comment by Iosybe** [comment]
Hoezo? De window var is een parameter van de callbacks.

**Comment by Boris00035** [comment]
we can just pass the window var to the custom init function that "declares" the callbacks, then the window doesnt have to be a global var
